##  Student name1 Genadi Birfir, Student name2 Niv kotek

# Lab 1 - node2vec

The files for this colab notebook are available on Moodle

In [2]:
!pip install node2vec

Requirement already satisfied: node2vec in /usr/local/lib/python3.11/dist-packages (0.5.0)
Requirement already satisfied: gensim<5.0.0,>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from node2vec) (4.3.3)
Requirement already satisfied: joblib<2.0.0,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from node2vec) (1.4.2)
Requirement already satisfied: networkx<4.0.0,>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from node2vec) (3.4.2)
Requirement already satisfied: numpy<2.0.0,>=1.24.0 in /usr/local/lib/python3.11/dist-packages (from node2vec) (1.26.4)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in /usr/local/lib/python3.11/dist-packages (from node2vec) (4.67.1)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim<5.0.0,>=4.3.0->node2vec) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim<5.0.0,>=4.3.0->node2vec) (7.1.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim<5.0.0,>=4.3.0->node2vec) (1.17.2)

In [3]:
import networkx as nx
from node2vec import Node2Vec
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

Create a graph

In [4]:
# load data
df = pd.read_csv('/content/MOT_edges.csv')
df

       Source  Target  PassengerNumber  ComplaintsNumber
0       41700   42834                3                 2
1       47266   42834                1                 1
2       41664   41576                4                 2
3       42289   41576                3                 1
4       41390   42713                2                 1
...       ...     ...              ...               ...
15394   57344   56690                7                 3
15395   57345   55224                1                 1
15396   58567   55224                1                 1
15397   58573   55224               48                 3
15398   58601   55224                6                 1

[15399 rows x 4 columns]

In [5]:
# create an undirected networkx graph
G = nx.from_pandas_edgelist(df, 'Source', 'Target')
G = nx.to_undirected(G)

In [6]:
n = G.number_of_nodes()
m = G.number_of_edges()
print("Number of nodes :", str(n))
print("Number of edges :", str(m))
print("Number of connected components :", str(nx.number_connected_components(G)))

Number of nodes : 6325
Number of edges : 10870
Number of connected components : 242

In [7]:
# generate walks
node2vec = Node2Vec(G, dimensions=64, walk_length=30, num_walks=20, workers=4)

Computing transition probabilities:   0%|          | 0/6325 [00:00<?, ?it/s]

In [8]:
# Embed nodes
model = node2vec.fit(window=10, min_count=1, batch_words=4)

In [9]:
# get node embeddings
model.wv.get_vector('41700')

array([ 0.32551712, -1.6206471 , -1.1865532 , -1.7720231 ,  0.9386059 ,
       -0.8517737 ,  1.2429701 ,  0.0659168 , -0.65108997,  0.57585835,
        0.9536106 ,  0.24380995, -0.90964985, -0.33372512,  0.18557394,
        0.70184755, -0.3138346 , -0.17800955,  0.2976573 ,  0.7018622 ,
        0.71019894, -0.7068118 , -0.748784  ,  0.2469628 , -0.73760337,
        0.70836234, -0.64938176,  1.2492728 ,  0.18727602, -0.8957684 ,
        0.13818945, -0.3594546 ,  0.9124876 , -0.10341596,  0.06378539,
        0.11599009, -1.4468108 ,  0.51115143, -0.69676334, -0.01057616,
        0.5395706 ,  0.41714394,  0.43726224,  0.02963277,  0.38707736,
        0.06573275, -0.49605548, -0.5774288 ,  0.770594  ,  0.15476237,
        0.44587943, -0.04895189,  0.77727   ,  0.6002624 , -0.5052703 ,
       -0.41688234,  0.3582261 ,  0.4170655 , -1.5498698 ,  0.38637903,
       -0.07509532, -0.1926712 ,  0.7386452 , -0.17165476], dtype=float32)

## use logostic regression to predict

In [10]:
nodes = list(G.nodes())
nodes

[41700,
 42834,
 47266,
 41664,
 41576,
 42289,
 41390,
 42713,
 42041,
 42709,
 47892,
 41483,
 41714,
 42159,
 41533,
 41575,
 41698,
 47392,
 42015,
 42571,
 42723,
 47222,
 47403,
 42977,
 42001,
 42242,
 43115,
 43078,
 47528,
 41208,
 41215,
 41209,
 41645,
 42333,
 43139,
 42171,
 41968,
 47497,
 41751,
 41246,
 40985,
 41060,
 42659,
 42501,
 41671,
 43114,
 42016,
 42853,
 42603,
 41068,
 41173,
 46203,
 43032,
 41188,
 43191,
 41190,
 42998,
 42827,
 42664,
 41260,
 43035,
 43009,
 41845,
 46234,
 41854,
 41758,
 50093,
 51564,
 51566,
 52964,
 51567,
 43663,
 40957,
 42182,
 43725,
 47232,
 41520,
 43713,
 42409,
 41521,
 41543,
 41670,
 41743,
 41764,
 42327,
 42406,
 43094,
 43127,
 43715,
 43722,
 43723,
 43726,
 43728,
 46207,
 46214,
 46215,
 46950,
 53344,
 53363,
 53364,
 53368,
 41128,
 40297,
 41704,
 43711,
 41210,
 41249,
 41692,
 42870,
 42987,
 43013,
 42345,
 43072,
 42937,
 40377,
 41296,
 42698,
 40583,
 520,
 3007,
 5200,
 638,
 1685,
 65135,
 5130,
 34002,
 5131,
 5132,
 31654,
 60001,
 61368,
 65134,
 22028,
 37779,
 41045,
 47409,
 42088,
 41735,
 1904,
 428,
 60878,
 42621,
 2899,
 42162,
 42388,
 161,
 61466,
 1552,
 1553,
 3374,
 4075,
 64006,
 4116,
 5668,
 61202,
 63907,
 63908,
 63911,
 63913,
 65240,
 65444,
 31143,
 32453,
 31051,
 31635,
 31585,
 31647,
 31611,
 31661,
 37624,
 38126,
 38135,
 38167,
 20037,
 20094,
 20147,
 20150,
 37660,
 20155,
 20162,
 20163,
 20330,
 21181,
 21265,
 21282,
 21286,
 21373,
 21538,
 22279,
 23064,
 25287,
 25639,
 26064,
 26143,
 26149,
 26172,
 26178,
 26461,
 26475,
 26516,
 26544,
 26550,
 26554,
 27058,
 27085,
 28525,
 28632,
 36136,
 36159,
 36173,
 36174,
 41896,
 47379,
 42351,
 42945,
 42674,
 78,
 5937,
 210,
 211,
 514,
 3824,
 516,
 522,
 523,
 524,
 527,
 541,
 680,
 1310,
 1328,
 1507,
 1956,
 2246,
 2836,
 3121,
 3327,
 3629,
 3634,
 4011,
 4115,
 4169,
 4216,
 5669,
 6012,
 9949,
 60413,
 41476,
 52378,
 42938,
 52133,
 43058,
 52114,
 51374,
 57305,
 1122,
 1415,
 61175,
 60868,
 60884,
 30156,
 31280,
 31277,
 31559,
 32550,
 37632,
 1637,
 5497,
 5461,
 6212,
 5494,
 6203,
 6245,
 647,
 1286,
 5601,
 5602,
 2602,
 4218,
 5510,
 5513,
 5514,
 5519,
 5587,
 5843,
 9859,
 5577,
 5579,
 61506,
 65139,
 65149,
 65150,
 20152,
 25953,
 20700,
 21466,
 21718,
 21584,
 21592,
 26806,
 36850,
 36855,
 20798,
 22556,
 31097,
 33286,
 31100,
 31283,
 32253,
 34232,
 38674,
 40397,
 40847,
 40528,
 42658,
 46177,
 34781,
 32117,
 38774,
 41869,
 40990,
 40955,
 41161,
 42346,
 11001,
 31075,
 11002,
 11003,
 11005,
 11006,
 11010,
 11013,
 12005,
 12708,
 13203,
 31230,
 31744,
 31750,
 32115,
 32116,
 32118,
 32128,
 32132,
 36432,
 36443,
 38063,
 289,
 41459,
 42689,
 42191,
 42362,
 42688,
 6071,
 20309,
 21379,
 25358,
 25430,
 25637,
 25644,
 31313,
 21639,
 31596,
 31653,
 31662,
 31898,
 36816,
 21230,
 36258,
 21354,
 22273,
 26946,
 31455,
 36172,
 36256,
 36266,
 36268,
 37571,
 21161,
 37785,
 21711,
 22942,
 31640,
 31476,
 33169,
 35084,
 35096,
 35097,
 35099,
 35101,
 38138,
 39083,
 30928,
 32423,
 37430,
 31643,
 32465,
 33170,
 33483,
 33734,
 34031,
 35093,
 37721,
 56132,
 52579,
 57821,
 37789,
 21370,
 21684,
 27063,
 37203,
 39751,
 59704,
 50739,
 59414,
 53094,
 51523,
 51577,
 52688,
 52950,
 55137,
 59707,
 59708,
 54196,
 51671,
 54200,
 4174,
 61362,
 31575,
 60473,
 63657,
 35139,
 60778,
 63636,
 35941,
 50074,
 47490,
 42990,
 51524,
 52326,
 53549,
 53576,
 53712,
 53713,
 54193,
 38002,
 38958,
 21378,
 25071,
 27997,
 26632,
 31091,
 21254,
 37644,
 31156,
 32022,
 32614,
 32011,
 32625,
 32674,
 32676,
 33567,
 34719,
 35366,
 35552,
 35560,
 35566,
 35571,
 35573,
 35627,
 35861,
 38520,
 38525,
 38530,
 38597,
 154,
 645,
 1556,
 34001,
 1683,
 2007,
 3142,
 31152,
 31165,
 34017,
 35109,
 35517,
 35526,
 35537,
 35569,
 35585,
 35586,
 35587,
 35594,
 35625,
 35628,
 38591,
 65340,
 65359,
 21023,
 38129,
 21028,
 21119,
 21221,
 21256,
 22930,
 26089,
 35547,
 26811,
 39685,
 32652,
 36365,
 21425,
 21195,
 63111,
 22955,
 22980,
 23014,
 23017,
 27010,
 27084,
 63227,
 63418,
 63098,
 63271,
 63411,
 63428,
 38160,
 38252,
 35397,
 20056,
 37995,
 20057,
 20058,
 21258,
 21558,
 21560,
 22276,
 22277,
 22970,
 22975,
 23051,
 23053,
 23055,
 26402,
 26520,
 26525,
 31741,
 32285,
 32445,
 32446,
 32447,
 32448,
 32449,
 32450,
 32451,
 35401,
 12071,
 32142,
 19988,
 32030,
 32207,
 52551,
 51704,
 42803,
 53791,
 54298,
 60262,
 60292,
 11011,
 31517,
 31530,
 32044,
 32254,
 32256,
 35232,
 35298,
 37476,
 37602,
 37626,
 21109,
 33512,
 35744,
 20068,
 26484,
 38699,
 20059,
 31329,
 20168,
 20200,
 20340,
 22972,
 26501,
 32969,
 34235,
 34270,
 34690,
 34696,
 35672,
 35673,
 35674,
 37707,
 38908,
 38945,
 1232,
 9936,
 33739,
 35055,
 60222,
 60237,
 60245,
 60249,
 60250,
 60290,
 60298,
 60354,
 60373,
 60374,
 60376,
 60387,
 60523,
 60663,
 65156,
 65384,
 800,
 4007,
 9855,
 60272,
 60276,
 60278,
 60285,
 60287,
 60303,
 60305,
 60307,
 60308,
 60310,
 60356,
 60358,
 60392,
 40320,
 43265,
 43137,
 51082,
 52154,
 51659,
 53947,
 54048,
 54225,
 55234,
 4009,
 1509,
 1862,
 3230,
 51661,
 52218,
 54183,
 57110,
 51040,
 51846,
 55642,
 51850,
 51105,
 41462,
 54054,
 54159,
 54220,
 54236,
 10430,
 35679,
 20001,
 20750,
 21472,
 33569,
 20026,
 26749,
 28642,
 51587,
 55417,
 52174,
 55332,
 52269,
 55048,
 55084,
 55115,
 55231,
 55253,
 55318,
 55380,
 55385,
 56876,
 31074,
 11012,
 11056,
 11057,
 11060,
 11357,
 11358,
 11359,
 11361,
 11362,
 11363,
 11364,
 11365,
 11367,
 11368,
 11571,
 11856,
 12295,
 12945,
 13175,
 13178,
 13304,
 13318,
 19180,
 21626,
 35863,
 26776,
 33872,
 36430,
 10311,
 16145,
 10346,
 13777,
 10347,
 10536,
 10537,
 11286,
 12084,
 12284,
 12287,
 12289,
 12292,
 12296,
 12829,
 13452,
 13475,
 14788,
 14798,
 14806,
 15518,
 15530,
 15982,
 16036,
 16161,
 19561,
 19911,
 13437,
 15343,
 13658,
 13907,
 38801,
 14838,
 14849,
 14851,
 14855,
 14856,
 14857,
 14878,
 15258,
 15260,
 15264,
 15265,
 15266,
 15269,
 15280,
 15566,
 15590,
 15624,
 16506,
 19204,
 31265,
 32208,
 35203,
 38464,
 20055,
 33440,
 27043,
 33154,
 33158,
 33313,
 33314,
 33315,
 33484,
 33614,
 36079,
 36271,
 36433,
 36434,
 36435,
 36436,
 39932,
 12072,
 30002,
 51074,
 56795,
 56819,
 53979,
 53984,
 54237,
 55256,
 55262,
 12358,
 15359,
 13107,
 14125,
 14330,
 14410,
 14414,
 15333,
 34222,
 65409,
 14035,
 10312,
 14094,
 14118,
 37996,
 15997,
 16170,
 16490,
 22282,
 22974,
 26977,
 36500,
 37128,
 10045,
 11433,
 14400,
 12355,
 12518,
 12545,
 12833,
 13418,
 16037,
 18075,
 41609,
 50723,
 56059,
 51213,
 51621,
 51662,
 51664,
 52383,
 52619,
 52691,
 52949,
 53345,
 54204,
 54706,
 57538,
 57664,
 57841,
 58002,
 59423,
 59444,
 669,
 15572,
 10004,
 13679,
 15514,
 15599,
 15554,
 15582,
 15591,
 15607,
 11356,
 15596,
 14931,
 11802,
 12128,
 15608,
 15067,
 19847,
 50315,
 59151,
 50474,
 50564,
 50598,
 50961,
 50615,
 50709,
 50767,
 50869,
 50956,
 51629,
 12132,
 15539,
 13102,
 10099,
 10137,
 10138,
 13808,
 13404,
 13864,
 15180,
 15211,
 15400,
 15636,
 15640,
 15861,
 31078,
 31151,
 32308,
 33113,
 35216,
 35293,
 37604,
 38505,
 10005,
 15449,
 11328,
 11436,
 15434,
 13566,
 13751,
 14349,
 14887,
 14927,
 15287,
 15300,
 15353,
 15625,
 16512,
 32148,
 32153,
 33702,
 10076,
 10856,
 11543,
 11548,
 11551,
 12615,
 12620,
 14540,
 14847,
 14912,
 14920,
 14926,
 14928,
 15277,
 15299,
 15573,
 15592,
 15693,
 16505,
 19735,
 20353,
 21342,
 21402,
 21487,
 19212,
 10173,
 14429,
 14183,
 10313,
 10491,
 10609,
 10649,
 16052,
 14015,
 14033,
 14331,
 15984,
 16438,
 10351,
 10233,
 10512,
 11347,
 12612,
 15602,
 10309,
 10793,
 10528,
 10630,
 10795,
 10636,
 13442,
 13850,
 13965,
 16171,
 19823,
 10385,
 15332,
 32250,
 33444,
 10383,
 19757,
 155,
 4170,
 5667,
 20092,
 23060,
 23062,
 26518,
 26538,
 33156,
 33184,
 34065,
 33189,
 33613,
 36077,
 ...]

In [11]:
# load data
df1 = pd.read_csv('/content/MOT_nodes4.csv')
df1

          Id  Y
0          1  1
1          2  0
2          3  1
3          4  0
4          5  1
...      ... ..
15394  36052  1
15395  36053  1
15396  36054  1
15397  36055  1
15398  36056  1

[15399 rows x 2 columns]

In [12]:
# define target variable

# create a list of nodes form the network
nodes = list(G.nodes())

# convert nodes into a dataframe
nodes_df = pd.DataFrame(nodes, columns=['node_name'])

# create a set of random lables
nodes_df['Y'] = df1['Y']
# count number of values in each class (0 or 1)
print(nodes_df['Y'].value_counts())

nodes_df

Y
1    5327
0     998
Name: count, dtype: int64

      node_name  Y
0         41700  1
1         42834  0
2         47266  1
3         41664  0
4         41576  1
...         ... ..
6320      56693  0
6321      57344  0
6322      58567  1
6323      58573  0
6324      58601  1

[6325 rows x 2 columns]

In [13]:
# create a dataframe with node embeddigns
node_embeddings = []

for node in nodes_df['node_name']:
  # Convert node to string before querying the model
  node_str = str(node)

  # Check if the node exists in the model's vocabulary
  if node_str in model.wv.key_to_index:
    node_embeddings.append(model.wv.get_vector(node_str))
  else:
    # Handle missing nodes (e.g., assign a default vector or skip)
    print(f"Node {node_str} not found in model vocabulary.")
    # Option 1: Assign a zero vector
    # node_embeddings.append(np.zeros(model.vector_size))
    # Option 2: Skip the node
    # pass

X = pd.DataFrame(node_embeddings)
X

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.325517,-1.620647,-1.186553,-1.772023,0.938606,-0.851774,1.242970,0.065917,-0.651090,0.575858,...,-0.505270,-0.416882,0.358226,0.417066,-1.549870,0.386379,-0.075095,-0.192671,0.738645,-0.171655
1,0.338098,-1.731896,-1.266091,-1.916005,0.985395,-0.924609,1.329664,0.079803,-0.674955,0.660788,...,-0.574875,-0.432672,0.354798,0.414425,-1.675247,0.432766,-0.078887,-0.198425,0.777922,-0.189834
2,0.322480,-1.654533,-1.219644,-1.794683,0.914896,-0.869803,1.271170,0.050081,-0.622182,0.594619,...,-0.504692,-0.405782,0.370353,0.418430,-1.553488,0.395953,-0.069791,-0.189314,0.723121,-0.181853
3,-0.092628,0.043133,0.690295,-0.328489,-0.420784,-0.468284,0.349852,0.161487,-0.450754,0.622294,...,-0.699454,-0.345274,0.402484,-0.107958,-0.729449,0.298101,-0.865606,-0.145673,-0.088631,-0.806878
4,-0.060832,-0.105594,0.576443,-0.327487,-0.386710,-0.331355,0.151259,0.146420,-0.303000,0.602004,...,-0.669885,-0.174884,0.426431,-0.158387,-0.459942,0.133201,-0.824673,-0.302447,-0.059340,-0.578299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6320,0.339813,-0.923646,-1.154908,-1.099547,0.071740,-0.403967,0.585844,-0.466408,-0.571818,1.031107,...,-1.928658,-0.299067,-0.056714,-0.328262,0.304309,0.276911,-0.090152,0.577841,0.701138,0.715537
6321,0.229902,-0.966723,-1.185037,-1.134509,-0.005229,-0.465486,0.594179,-0.575910,-0.633937,1.107566,...,-1.935006,-0.216653,0.065437,-0.464570,0.276709,0.305010,-0.003642,0.368662,0.679867,0.699423
6322,0.548674,-0.474473,-0.224058,-0.703078,-0.539491,1.086570,0.103432,0.144456,-0.314937,0.567776,...,-1.188970,-0.113460,0.172503,-0.449380,-0.400237,-0.473138,-0.502060,0.208372,0.716638,-0.222654
6323,0.502529,-0.514469,-0.414220,-0.562349,-0.442491,0.880465,0.296857,0.225623,-0.410194,0.461352,...,-1.364682,0.105524,0.092950,-0.604717,-0.410845,-0.573471,-0.669918,0.179095,0.885075,-0.321835
6324,0.596105,-0.332307,-0.215710,-0.573020,-0.129256,0.832861,0.326652,0.093694,-0.348907,0.456502,...,-1.419257,0.224330,0.400687,-0.639897,-0.353628,-0.330784,-0.319956,0.482626,0.700045,-0.451993

In [57]:
y = nodes_df['Y']
from imblearn.combine import SMOTETomek
# Apply SMOTE + Tomek Links
smote_tomek = SMOTETomek(sampling_strategy='auto', random_state=42)
X_resampled, y_resampled = smote_tomek.fit_resample(X, y)

X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(8443, 64) (8443,)
(2111, 64) (2111,)

In [58]:
# Train a logistic regression model
logreg = LogisticRegression(max_iter=300)
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=300)

In [59]:
y_pred = logreg.predict(X_test)
print('Accuracy: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy: 0.60

In [60]:
from sklearn.metrics import confusion_matrix

print('Confusion Matrix [Actual (rows) X Predicted(columns)]')
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

Confusion Matrix [Actual (rows) X Predicted(columns)]
[[618 425]
 [413 655]]

In [61]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test,y_pred))
print('accuracy_score', accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.60      0.59      0.60      1043
           1       0.61      0.61      0.61      1068

    accuracy                           0.60      2111
   macro avg       0.60      0.60      0.60      2111
weighted avg       0.60      0.60      0.60      2111

accuracy_score 0.6030317385125533